"""create ton_tokens table

Revision ID: b573492b9248
Revises: a0ea7df0c7c6
Create Date: 2024-07-22 01:37:23.448401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b573492b9248"
down_revision: Union[str, None] = "a0ea7df0c7c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tontokens",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("jetton_master_address", sa.String(), nullable=False),
        sa.Column("sticker_file_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jetton_master_address"),
        sa.UniqueConstraint("sticker_file_id"),
        sa.UniqueConstraint("ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tontokens")
    # ### end Alembic commands ###
